apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api

    spec:
      containers:
      - name: api-container
        image: api-service:v1

        imagePullPolicy: Never

        env:
        - name: LICENSE
          value: accept

        ports:
        - containerPort: 7800
