dynamicr#targetUrl=http://backend-service:7800/simulator
dynamicr#HTTP Input.URLSpecifier=/projectd
dynamicr#SOAP Request.webServiceURL=http://localhost:7800/simulato
dynamicr#SOAP Request.sslProtocol=TLS
dynamicr#SOAP Request.validateMaster=none
